stages:
  plot:
    cmd: python plot.py
    deps:
      - plot.py
    outs:
      - figs
  build-paper-2:
    cmd: >
      calkit runenv -n latex --
      latexmk -cd -interaction=nonstopmode -pdf paper-2/paper.tex
    deps:
      - .calkit/environments/latex.yaml
      - paper-2/paper.tex
    outs:
      - paper-2/paper.pdf
